# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addcourse_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addCourseDialog(object):
    def setupUi(self, addCourseDialog):
        addCourseDialog.setObjectName("addCourseDialog")
        addCourseDialog.resize(489, 257)
        self.courseCodeField = QtWidgets.QLineEdit(addCourseDialog)
        self.courseCodeField.setGeometry(QtCore.QRect(130, 40, 221, 31))
        self.courseCodeField.setObjectName("courseCodeField")
        self.label_2 = QtWidgets.QLabel(addCourseDialog)
        self.label_2.setGeometry(QtCore.QRect(40, 50, 81, 20))
        self.label_2.setObjectName("label_2")
        self.cancelCourse = QtWidgets.QPushButton(addCourseDialog)
        self.cancelCourse.setGeometry(QtCore.QRect(150, 180, 192, 27))
        self.cancelCourse.setStyleSheet("background-color:rgb(255, 80, 64);\n"
"color: white")
        self.cancelCourse.setObjectName("cancelCourse")
        self.addCourseConfirm = QtWidgets.QPushButton(addCourseDialog)
        self.addCourseConfirm.setGeometry(QtCore.QRect(150, 150, 192, 27))
        self.addCourseConfirm.setStyleSheet("background-color:rgb(85, 207, 8);\n"
"color: white;")
        self.addCourseConfirm.setObjectName("addCourseConfirm")
        self.label_3 = QtWidgets.QLabel(addCourseDialog)
        self.label_3.setGeometry(QtCore.QRect(40, 90, 101, 20))
        self.label_3.setObjectName("label_3")
        self.courseNameField = QtWidgets.QLineEdit(addCourseDialog)
        self.courseNameField.setGeometry(QtCore.QRect(130, 80, 321, 31))
        self.courseNameField.setObjectName("courseNameField")

        self.retranslateUi(addCourseDialog)
        QtCore.QMetaObject.connectSlotsByName(addCourseDialog)

    def retranslateUi(self, addCourseDialog):
        _translate = QtCore.QCoreApplication.translate
        addCourseDialog.setWindowTitle(_translate("addCourseDialog", "Add Course"))
        self.label_2.setText(_translate("addCourseDialog", "Course Code"))
        self.cancelCourse.setText(_translate("addCourseDialog", "Cancel"))
        self.addCourseConfirm.setText(_translate("addCourseDialog", "Add Course"))
        self.label_3.setText(_translate("addCourseDialog", "Course Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addCourseDialog = QtWidgets.QDialog()
    ui = Ui_addCourseDialog()
    ui.setupUi(addCourseDialog)
    addCourseDialog.show()
    sys.exit(app.exec_())
