# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addstudent_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addStudentDialog(object):
    def setupUi(self, addStudentDialog):
        addStudentDialog.setObjectName("addStudentDialog")
        addStudentDialog.resize(486, 400)
        self.addStudent_confirm = QtWidgets.QPushButton(addStudentDialog)
        self.addStudent_confirm.setGeometry(QtCore.QRect(150, 320, 192, 27))
        self.addStudent_confirm.setStyleSheet("background-color:rgb(85, 207, 8);\n"
"color: white;")
        self.addStudent_confirm.setObjectName("addStudent_confirm")
        self.cancelAdd = QtWidgets.QPushButton(addStudentDialog)
        self.cancelAdd.setGeometry(QtCore.QRect(150, 350, 192, 27))
        self.cancelAdd.setStyleSheet("background-color:rgb(255, 80, 64);\n"
"color: white")
        self.cancelAdd.setObjectName("cancelAdd")
        self.groupBox = QtWidgets.QGroupBox(addStudentDialog)
        self.groupBox.setGeometry(QtCore.QRect(30, 31, 421, 281))
        self.groupBox.setObjectName("groupBox")
        self.addNameField = QtWidgets.QLineEdit(self.groupBox)
        self.addNameField.setGeometry(QtCore.QRect(100, 40, 301, 31))
        self.addNameField.setObjectName("addNameField")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(38, 50, 55, 16))
        self.label.setObjectName("label")
        self.addIDNumField_Year = QtWidgets.QLineEdit(self.groupBox)
        self.addIDNumField_Year.setGeometry(QtCore.QRect(100, 80, 91, 31))
        self.addIDNumField_Year.setMaxLength(4)
        self.addIDNumField_Year.setObjectName("addIDNumField_Year")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 61, 16))
        self.label_3.setObjectName("label_3")
        self.courseComboBox = QtWidgets.QComboBox(self.groupBox)
        self.courseComboBox.setGeometry(QtCore.QRect(100, 200, 201, 22))
        self.courseComboBox.setObjectName("courseComboBox")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(34, 203, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(40, 170, 31, 16))
        self.label_5.setObjectName("label_5")
        self.genderBox = QtWidgets.QGroupBox(self.groupBox)
        self.genderBox.setGeometry(QtCore.QRect(201, 125, 201, 61))
        self.genderBox.setObjectName("genderBox")
        self.maleRadBut = QtWidgets.QRadioButton(self.genderBox)
        self.maleRadBut.setGeometry(QtCore.QRect(10, 30, 92, 20))
        self.maleRadBut.setObjectName("maleRadBut")
        self.femaleRadBut = QtWidgets.QRadioButton(self.genderBox)
        self.femaleRadBut.setGeometry(QtCore.QRect(80, 30, 92, 20))
        self.femaleRadBut.setObjectName("femaleRadBut")
        self.ageSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.ageSpinBox.setGeometry(QtCore.QRect(100, 165, 91, 21))
        self.ageSpinBox.setSpecialValueText("")
        self.ageSpinBox.setMinimum(0)
        self.ageSpinBox.setProperty("value", 18)
        self.ageSpinBox.setObjectName("ageSpinBox")
        self.yearSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.yearSpinBox.setGeometry(QtCore.QRect(100, 130, 91, 22))
        self.yearSpinBox.setSpecialValueText("")
        self.yearSpinBox.setMinimum(1)
        self.yearSpinBox.setMaximum(4)
        self.yearSpinBox.setObjectName("yearSpinBox")
        self.addIDNumField_Number = QtWidgets.QLineEdit(self.groupBox)
        self.addIDNumField_Number.setGeometry(QtCore.QRect(210, 80, 91, 31))
        self.addIDNumField_Number.setInputMask("")
        self.addIDNumField_Number.setMaxLength(4)
        self.addIDNumField_Number.setObjectName("addIDNumField_Number")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(190, 90, 21, 16))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(addStudentDialog)
        QtCore.QMetaObject.connectSlotsByName(addStudentDialog)

    def retranslateUi(self, addStudentDialog):
        _translate = QtCore.QCoreApplication.translate
        addStudentDialog.setWindowTitle(_translate("addStudentDialog", "Add Student"))
        self.addStudent_confirm.setText(_translate("addStudentDialog", "Add Student"))
        self.cancelAdd.setText(_translate("addStudentDialog", "Cancel"))
        self.groupBox.setTitle(_translate("addStudentDialog", "Add Student"))
        self.addNameField.setPlaceholderText(_translate("addStudentDialog", "Enter Full Name"))
        self.label.setText(_translate("addStudentDialog", "Name"))
        self.addIDNumField_Year.setPlaceholderText(_translate("addStudentDialog", "XXXX"))
        self.label_2.setText(_translate("addStudentDialog", "ID Number"))
        self.label_3.setText(_translate("addStudentDialog", "Year Level"))
        self.label_4.setText(_translate("addStudentDialog", "Course"))
        self.label_5.setText(_translate("addStudentDialog", "Age"))
        self.genderBox.setTitle(_translate("addStudentDialog", "Gender"))
        self.maleRadBut.setText(_translate("addStudentDialog", "Male"))
        self.femaleRadBut.setText(_translate("addStudentDialog", "Female"))
        self.addIDNumField_Number.setPlaceholderText(_translate("addStudentDialog", "XXXX"))
        self.label_6.setText(_translate("addStudentDialog", "-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addStudentDialog = QtWidgets.QDialog()
    ui = Ui_addStudentDialog()
    ui.setupUi(addStudentDialog)
    addStudentDialog.show()
    sys.exit(app.exec_())
