# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editcourse_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editcourse(object):
    def setupUi(self, editcourse):
        editcourse.setObjectName("editcourse")
        editcourse.resize(489, 281)
        self.editCourseConfirm = QtWidgets.QPushButton(editcourse)
        self.editCourseConfirm.setGeometry(QtCore.QRect(150, 200, 192, 27))
        self.editCourseConfirm.setStyleSheet("background-color:rgb(255, 150, 30);\n"
"color: white;")
        self.editCourseConfirm.setObjectName("editCourseConfirm")
        self.cancelEditCourse = QtWidgets.QPushButton(editcourse)
        self.cancelEditCourse.setGeometry(QtCore.QRect(150, 230, 192, 27))
        self.cancelEditCourse.setStyleSheet("background-color:rgb(255, 80, 64);\n"
"color: white")
        self.cancelEditCourse.setObjectName("cancelEditCourse")
        self.groupBox = QtWidgets.QGroupBox(editcourse)
        self.groupBox.setGeometry(QtCore.QRect(30, 30, 431, 151))
        self.groupBox.setObjectName("groupBox")
        self.courseNameField = QtWidgets.QLineEdit(self.groupBox)
        self.courseNameField.setGeometry(QtCore.QRect(107, 90, 300, 31))
        self.courseNameField.setObjectName("courseNameField")
        self.courseCodeField = QtWidgets.QLineEdit(self.groupBox)
        self.courseCodeField.setGeometry(QtCore.QRect(107, 40, 300, 31))
        self.courseCodeField.setObjectName("courseCodeField")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(21, 46, 80, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(21, 97, 80, 20))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(editcourse)
        QtCore.QMetaObject.connectSlotsByName(editcourse)

    def retranslateUi(self, editcourse):
        _translate = QtCore.QCoreApplication.translate
        editcourse.setWindowTitle(_translate("editcourse", "Edit Course"))
        self.editCourseConfirm.setText(_translate("editcourse", "Edit Course"))
        self.cancelEditCourse.setText(_translate("editcourse", "Cancel"))
        self.groupBox.setTitle(_translate("editcourse", "Edit Course"))
        self.label_2.setText(_translate("editcourse", "Course Code"))
        self.label_3.setText(_translate("editcourse", "Course Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editcourse = QtWidgets.QDialog()
    ui = Ui_editcourse()
    ui.setupUi(editcourse)
    editcourse.show()
    sys.exit(app.exec_())
