# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editstudent_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editStudentDialog(object):
    def setupUi(self, editStudentDialog):
        editStudentDialog.setObjectName("editStudentDialog")
        editStudentDialog.resize(486, 309)
        self.editStudent_confirm = QtWidgets.QPushButton(editStudentDialog)
        self.editStudent_confirm.setGeometry(QtCore.QRect(150, 240, 192, 27))
        self.editStudent_confirm.setStyleSheet("background-color:rgb(255, 150, 30);\n"
"color: white;")
        self.editStudent_confirm.setObjectName("editStudent_confirm")
        self.cancelAdd = QtWidgets.QPushButton(editStudentDialog)
        self.cancelAdd.setGeometry(QtCore.QRect(150, 270, 192, 27))
        self.cancelAdd.setStyleSheet("background-color:rgb(255, 80, 64);\n"
"color: white")
        self.cancelAdd.setObjectName("cancelAdd")
        self.groupBox = QtWidgets.QGroupBox(editStudentDialog)
        self.groupBox.setGeometry(QtCore.QRect(30, 31, 421, 201))
        self.groupBox.setObjectName("groupBox")
        self.addNameField = QtWidgets.QLineEdit(self.groupBox)
        self.addNameField.setGeometry(QtCore.QRect(100, 40, 301, 31))
        self.addNameField.setObjectName("addNameField")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(38, 50, 55, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(29, 90, 61, 16))
        self.label_3.setObjectName("label_3")
        self.courseComboBox = QtWidgets.QComboBox(self.groupBox)
        self.courseComboBox.setGeometry(QtCore.QRect(99, 160, 201, 22))
        self.courseComboBox.setObjectName("courseComboBox")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(33, 163, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(39, 130, 31, 16))
        self.label_5.setObjectName("label_5")
        self.genderBox = QtWidgets.QGroupBox(self.groupBox)
        self.genderBox.setGeometry(QtCore.QRect(200, 85, 201, 61))
        self.genderBox.setObjectName("genderBox")
        self.maleRadBut = QtWidgets.QRadioButton(self.genderBox)
        self.maleRadBut.setGeometry(QtCore.QRect(10, 30, 92, 20))
        self.maleRadBut.setObjectName("maleRadBut")
        self.femaleRadBut = QtWidgets.QRadioButton(self.genderBox)
        self.femaleRadBut.setGeometry(QtCore.QRect(80, 30, 92, 20))
        self.femaleRadBut.setObjectName("femaleRadBut")
        self.ageSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.ageSpinBox.setGeometry(QtCore.QRect(99, 125, 91, 21))
        self.ageSpinBox.setSpecialValueText("")
        self.ageSpinBox.setMinimum(0)
        self.ageSpinBox.setProperty("value", 18)
        self.ageSpinBox.setObjectName("ageSpinBox")
        self.yearSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.yearSpinBox.setGeometry(QtCore.QRect(99, 90, 91, 22))
        self.yearSpinBox.setSpecialValueText("")
        self.yearSpinBox.setMinimum(1)
        self.yearSpinBox.setMaximum(4)
        self.yearSpinBox.setObjectName("yearSpinBox")

        self.retranslateUi(editStudentDialog)
        QtCore.QMetaObject.connectSlotsByName(editStudentDialog)

    def retranslateUi(self, editStudentDialog):
        _translate = QtCore.QCoreApplication.translate
        editStudentDialog.setWindowTitle(_translate("editStudentDialog", "Edit Student"))
        self.editStudent_confirm.setText(_translate("editStudentDialog", "Edit Student"))
        self.cancelAdd.setText(_translate("editStudentDialog", "Cancel"))
        self.groupBox.setTitle(_translate("editStudentDialog", "Edit Student"))
        self.label.setText(_translate("editStudentDialog", "Name"))
        self.label_3.setText(_translate("editStudentDialog", "Year Level"))
        self.label_4.setText(_translate("editStudentDialog", "Course"))
        self.label_5.setText(_translate("editStudentDialog", "Age"))
        self.genderBox.setTitle(_translate("editStudentDialog", "Gender"))
        self.maleRadBut.setText(_translate("editStudentDialog", "Male"))
        self.femaleRadBut.setText(_translate("editStudentDialog", "Female"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editStudentDialog = QtWidgets.QDialog()
    ui = Ui_editStudentDialog()
    ui.setupUi(editStudentDialog)
    editStudentDialog.show()
    sys.exit(app.exec_())
